version: "3.9"
services:
  app:
    build:
      context: "./"
    ports:
    - "127.0.0.1:8080:8080"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "raktrdb"
    ports:
    - "127.0.0.1:5432:5432"
