version: "3.9"
services:
  backend:
    build:
      context: "./backend"
    ports:
    - "127.0.0.1:8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: "./frontend"
    ports:
    - "127.0.0.1:80:80"
    depends_on:
      - backend
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "raktrdb"
    ports:
    - "127.0.0.1:5432:5432"